// ESTE ARQUIVO É MANTIDO APENAS PELAS CONSTANTES (TableNames)
// O CLIENTE DYNAMODB FOI REMOVIDO PARA EVITAR VAZAMENTO DE CREDENCIAIS
// TODAS AS OPERAÇÕES DE BANCO SÃO FEITAS VIA SERVER ACTIONS

export const TABLE_PREFIX = 'ShoppingIntranet_'

export const TableNames = {
  USERS: `${TABLE_PREFIX}Users`,
  PROPERTIES: `${TABLE_PREFIX}Properties`,
  STORES: `${TABLE_PREFIX}Stores`,
  CLIENTS: `${TABLE_PREFIX}Clients`,
  TASKS: `${TABLE_PREFIX}Tasks`,
  EVENTS: `${TABLE_PREFIX}Events`,
  NOTIFICATIONS: `${TABLE_PREFIX}Notifications`,
  LOGS: `${TABLE_PREFIX}Logs`,
  FLOOR_PLANS: `${TABLE_PREFIX}FloorPlans`,
  LEADS: `${TABLE_PREFIX}Leads`,
}
